version: "3.8"

services:
  db-debug:
    image: postgres:13
    restart: always
    container_name: 'testwork-postgres'
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
      
  
networks:
  backend: {}
